version: '3.3'

services:
  fermo_gui:
    build:
      context: .
      dockerfile: ./compose/fermo_gui/Dockerfile
    restart: unless-stopped
    ports:
      - 8001:8001
  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - 1338:80
    depends_on:
      - fermo_gui